# Decision Trees

   Decision tree is a predictive model used in machine learning to classify instances by sorting tham down the tree from root to a leaf node. A decison is also reffered to as a classification tree or a reduction tree. According to Science direct Decision Tree article "Building a decision tree that is consistent with a given data set is easy. The challenge lies in building good decision trees, which typically means the smallest decision trees". There are packages that have been implemented to make this alot easier and even gives a visual. 

|![Clustering](img/img.png) |
|:--:| 
|*Decision Tree Example*|

    I will be using SKLearn Decision Tree Classifier package and to train my data I will also be using SKLearns Train Test Split. 

In [19]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.tree import export_graphviz

In [2]:
'''
    Importing iris data set from sklearn dataset
'''

data = datasets.load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [3]:
'''
    Seperating the data for later usage
'''

train_df = data['data']
label_df = data['target']

In [4]:
'''
   Getting our training labels to use when implementing Decision Tree
'''

x_train, x_test, y_train, y_test = train_test_split(train_df, label_df, random_state   = 1)

In [5]:
'''
    Using the Decision Tree Classifier to train Iris data
'''

clf = DecisionTreeClassifier()
clf.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [6]:
'''
    Using pred to put in our confusion matrix 
'''

y_pred = clf.predict(x_train)
pred = clf.predict(x_test)

In [7]:
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.94      0.97        16
           2       0.90      1.00      0.95         9

    accuracy                           0.97        38
   macro avg       0.97      0.98      0.97        38
weighted avg       0.98      0.97      0.97        38



In [32]:
'''
    Using GraphViz to generate and import a decision tree model based on the iris data set
'''


#pip install pydotplus
import pydotplus
import graphviz

dot_data = export_graphviz(clf, out_file=None, feature_names=data.feature_names, class_names=data.target_names)
graph = pydotplus.graph_from_dot_data(dot_data)
g = graphviz.Source(dot_data)
g.view()

'Source.gv.pdf'

    Above I have displayed the decision tree produced by using sklearns package Decision Tree Classifier
    
    Things to take into account when classifying the Decision Tree
    
    - Root Node: The top-most decision node in a decision tree
    - Decision Node: A tree node or parent node that splits into one or more child nodes
    - Leaf or Termianal Node: Bottom nodes(dont split any further)
    - Splitting: Process of dividing a node into two or more child nodes
    - Prunning: The opposite of splitting. removing the child nodes

### Refrences:
#### 1. https://scikit-learn.org/stable/modules/generated/sklearn.tree.export_graphviz.html
#### 2. https://www.hackerearth.com/practice/machine-learning/machine-learning-algorithms/ml-decision-tree/tutorial/
#### 3. https://heartbeat.fritz.ai/implementing-regression-using-a-decision-tree-and-scikit-learn-ac98552b43d7